# Generated by Django 5.2.4 on 2025-07-23 14:21

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[common.validators.FileSizeValidator(5)])),
                ('bio', models.CharField(blank=True, help_text='Brief bio about yourself', max_length=300, null=True)),
            ],
        ),
    ]
