# Generated by Django 5.2.4 on 2025-08-05 20:30

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[common.validators.FileSizeValidator(5)], verbose_name='profile_picture'),
        ),
    ]
