# Generated by Django 5.2.4 on 2025-08-02 19:27

import django.core.validators
import django.db.models.deletion
import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_tags'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_bleach.models.BleachField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game'),
        ),
    ]
