# Generated by Django 5.2.4 on 2025-08-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='games',
        ),
    ]
