# Generated by Django 5.2.4 on 2025-07-29 16:17

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games_images/', validators=[common.validators.FileSizeValidator(5)]),
        ),
    ]
