# Generated by Django 5.2.4 on 2025-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_image'),
        ('tags', '0002_remove_tag_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='tags.tag'),
        ),
    ]
