# Generated by Django 5.2.4 on 2025-08-05 19:43

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games_images/', validators=[common.validators.FileSizeValidator(5)]),
        ),
    ]
