# Generated by Django 5.2.4 on 2025-08-05 20:30

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[common.validators.FileSizeValidator(5)], verbose_name='image'),
        ),
    ]
